"""Constants for the Plenitude add-on service.

Auto-generated by scripts/sync_api.sh — DO NOT EDIT.
Mirror of the keys needed by the api/ modules, without HA-specific config keys.
"""
from __future__ import annotations

KRAKEN_GRAPHQL_URL = "https://api.plenitudefr-kraken.energy/v1/graphql/"
PORTAL_BASE_URL = "https://espace-client.eniplenitude.fr"
PORTAL_CONTRACT_PATH = "/contrat"
USER_AGENT = "plenitude2mqtt/0.1.0 (+https://github.com/williamboglietti/plenitude-ha)"
