#!/usr/bin/env bash
# Verify the add-on's API client copy is byte-identical to the custom integration's,
# and that the auto-generated const.py matches what sync_api.sh would produce.
# Used by CI to prevent drift.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="${REPO_ROOT}/custom_components/plenitude"
DST="${REPO_ROOT}/addon/plenitude2mqtt/service"

# shellcheck source=_lib.sh
. "${REPO_ROOT}/scripts/_lib.sh"

fail=0

for f in api/kraken.py api/portal.py api/rsc_parser.py api/__init__.py cost.py models.py; do
    if ! diff -q "${SRC}/${f}" "${DST}/${f}" > /dev/null; then
        echo "✗ ${f} differs between custom_components/ and addon/"
        diff "${SRC}/${f}" "${DST}/${f}" || true
        fail=1
    fi
done

# const.py is auto-generated by sync_api.sh and committed. Re-generate it into a
# temp file and confirm the committed copy still matches.
expected_const="$(mktemp)"
trap 'rm -f "${expected_const}"' EXIT
gen_const_py > "${expected_const}"
if ! diff -q "${expected_const}" "${DST}/const.py" > /dev/null; then
    echo "✗ service/const.py differs from sync_api.sh output (manual edit?)"
    diff "${expected_const}" "${DST}/const.py" || true
    fail=1
fi

if [ ${fail} -eq 0 ]; then
    echo "✓ All shared files are in sync."
else
    echo ""
    echo "Run: ${REPO_ROOT}/scripts/sync_api.sh"
    exit 1
fi
