#!/usr/bin/env bash
# Sync the API client + shared models from the custom integration into the add-on.
# Run after any edit to custom_components/plenitude/api/, cost.py, or models.py.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="${REPO_ROOT}/custom_components/plenitude"
DST="${REPO_ROOT}/addon/plenitude2mqtt/service"

# Copy api/ verbatim
rm -rf "${DST}/api"
mkdir -p "${DST}/api"
cp "${SRC}/api/"*.py "${DST}/api/"

# Copy cost.py and models.py verbatim
cp "${SRC}/cost.py" "${DST}/cost.py"
cp "${SRC}/models.py" "${DST}/models.py"

# Auto-generate a minimal const.py in the add-on (mirror of the keys api/ needs):
cat > "${DST}/const.py" <<'EOF'
"""Constants for the Plenitude add-on service.

Auto-generated by scripts/sync_api.sh — DO NOT EDIT.
Mirror of the keys needed by the api/ modules, without HA-specific config keys.
"""
from __future__ import annotations

KRAKEN_GRAPHQL_URL = "https://api.plenitudefr-kraken.energy/v1/graphql/"
PORTAL_BASE_URL = "https://espace-client.eniplenitude.fr"
PORTAL_CONTRACT_PATH = "/contrat"
USER_AGENT = "plenitude2mqtt/0.1.0 (+https://github.com/williamboglietti/plenitude-ha)"
EOF

echo "✓ Synced api/, cost.py, models.py from custom_components/plenitude/ to addon/plenitude2mqtt/service/"
